const COMMENT_TEXT_MIN = 5;
const COMMENT_TEXT_MAX = 1024;

const COMMENT_RATING_MIN = 1;
const COMMENT_RATING_MAX = 5;
const COMMENT_OBJECT_ID_HEX_MAX = 24;

export { COMMENT_TEXT_MIN, COMMENT_TEXT_MAX, COMMENT_RATING_MIN, COMMENT_RATING_MAX, COMMENT_OBJECT_ID_HEX_MAX };
