const OFFER_NAME_MIN = 10;
const OFFER_NAME_MAX = 100;
const OFFER_DESC_MIN = 20;
const OFFER_DESC_MAX = 1024;
const OFFER_PRICE_MIN = 100;
const OFFER_PRICE_MAX = 100000;
const OFFER_BEDROOMS_MIN = 1;
const OFFER_BEDROOMS_MAX = 8;
const OFFER_GUESTS_MIN = 1;
const OFFER_GUESTS_MAX = 10;

export { OFFER_NAME_MIN, OFFER_NAME_MAX, OFFER_DESC_MIN, OFFER_DESC_MAX, OFFER_PRICE_MIN, OFFER_PRICE_MAX, OFFER_BEDROOMS_MIN, OFFER_BEDROOMS_MAX, OFFER_GUESTS_MIN,OFFER_GUESTS_MAX };
