### Getting all offers (?limit=number can be used)
GET http://localhost:4000/offers
Accept: application/json
Authorization: Bearer

### Getting an offer by id (full data)
GET http://localhost:4000/offers/65caa630ae538f90a64b3c9d
Accept: application/json

### Getting premium offers by city
GET http://localhost:4000/offers/premium?city=Cologne
Accept: application/json

### Getting premium offers by city
GET http://localhost:4000/offers/favourites
Accept: application/json
Authorization: Bearer

### Adding an user offer
POST http://localhost:4000/offers/create
Content-Type: application/json
Authorization: Bearer

{
  "name": "Snooze Lodge",
  "price": 31405,
  "type": "room",
  "isFavourite": false,
  "isPremium": true,
  "postDate": "2024-10-07",
  "city": "Paris",
  "previewUrl": "https://picsum.photos/200/300/?blur",
  "rating": 0,
  "commentsCount": 0,
  "description": "Vela is located in beautiful Monteverde, famous for its rare and gorgeous cloud forest and friendly community.",
  "bedrooms": 2,
  "guests": 8,
  "urls": [
    "https://picsum.photos/200/300/?blur",
    "https://picsum.photos/200",
    "https://picsum.photos/200/300?grayscale",
    "https://picsum.photos/id/237/200/300",
    "https://picsum.photos/200/300.jpg",
    "https://picsum.photos/seed/picsum/200/300"
  ],
  "facilities": [
    "Breakfast",
    "Fridge"
  ],
  "location": {
    "long": 0.837,
    "lat": -48.838
  }
}

### Updating an existing offer
PATCH http://localhost:4000/offers/patch/65caa630ae538f90a64b3c9d
Content-Type: application/json
Authorization: Bearer

{
  "name": "New name",
  "price": 10000000
}

### Deliting an existing offer
DELETE http://localhost:4000/offers/delete/65caa630ae538f90a64b3c9d
Content-Type: application/json
Authorization: Bearer
