const USER_NAME_MIN = 1;
const USER_NAME_MAX = 15;

const USER_PASSWORD_MIN = 6;
const USER_PASSWORD_MAX = 12;
const USER_OBJECT_ID_HEX_MAX = 24;

export { USER_NAME_MIN, USER_NAME_MAX, USER_PASSWORD_MIN, USER_PASSWORD_MAX, USER_OBJECT_ID_HEX_MAX };
